version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build the application image
      - run: docker build --build-arg goal=deploy -t stephub/spring-provider:$CIRCLE_BRANCH .