version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build the application image
      - run: docker build -e BINTRAY_USERNAME=$BINTRAY_USERNAME -e BINTRAY_PASSWORD=$BINTRAY_PASSWORD --build-arg goal=deploy -t stephub/spring-provider:$CIRCLE_BRANCH .