version: 2
jobs:
  build:
    machine: true
    environment:
      GOAL: package
    steps:
      - checkout
      - run: docker build --build-arg version=$CIRCLE_BRANCH --build-arg goal=$GOAL -t stephub/spring-provider:$CIRCLE_BRANCH .
  build-and-deploy:
    machine: true
    environment:
      GOAL: deploy
    steps:
      - checkout
      - run: docker build --build-arg version=$CIRCLE_TAG --build-arg repo_username=$BINTRAY_USERNAME --build-arg repo_password=$BINTRAY_PASSWORD --build-arg goal=$GOAL -t stephub/spring-provider:$CIRCLE_TAG .
workflows:
  version: 2
  branch-build:
    jobs:
      - build
  release-build:
    jobs:
      - build-and-deploy:
          filters:
            tags:
              only: /^[0-9\.]+/
            branches:
              ignore: /.*/